# Generated by Django 4.0.6 on 2022-09-23 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=50)),
                ('course_fee_01', models.CharField(max_length=10)),
                ('course_fee_03', models.CharField(max_length=10)),
                ('course_fee_06', models.CharField(max_length=10)),
                ('course_desc', models.TextField()),
                ('slug', models.SlugField()),
            ],
        ),
    ]
