# Generated by Django 4.0.6 on 2022-09-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_course_fee_1_not_course_fee_3_not'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='fee_6_not',
            field=models.CharField(default='24999/-', max_length=10),
        ),
    ]
