# Generated by Django 4.0.6 on 2022-09-23 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_course_fee_6_not'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='fee_6_not',
            field=models.CharField(default='34999/-', max_length=10),
        ),
    ]
