# Generated by Django 4.0.6 on 2022-09-23 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_alter_course_fee_6_not'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='git_img',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
