# Generated by Django 4.0.6 on 2022-09-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_course_git_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_cont',
            field=models.TextField(blank=True, null=True),
        ),
    ]
