# Generated by Django 4.0.6 on 2022-09-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_course_course_cont'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_desc',
            new_name='course_desc_01',
        ),
        migrations.AddField(
            model_name='course',
            name='course_desc_02',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='course_heading_01',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='course_heading_02',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
