# Generated by Django 4.0.6 on 2022-09-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('cert_number', models.CharField(max_length=20)),
                ('cert_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
