# Generated by Django 4.0.6 on 2022-09-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
