# Generated by Django 4.0.6 on 2022-09-13 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_certificate_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='student_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
