# Generated by Django 4.0.6 on 2022-09-14 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_certificate_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='gdrive_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='cert_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
