# Generated by Django 4.0.6 on 2022-09-23 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.AddField(
            model_name='message',
            name='phone',
            field=models.CharField(default='', max_length=15),
        ),
    ]
